from turtle import Turtle

t = Turtle()
t.speed(1)
t.pensize(3)


# letra A
def a():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(90)
    t.back(90)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.color('white')
    t.forward(50)


# letra B
def b():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(80)
    t.right(45)
    t.forward(10)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.forward(10)
    t.right(45)
    t.forward(80)
    t.back(80)
    t.right(180)
    t.right(45)
    t.forward(20)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.forward(20)
    t.right(45)
    t.forward(80)
    t.back(80)
    t.color('white')
    t.back(60)
    t.color('white')
    t.right(180)
    t.forward(50)

# letra E
def e():
    t.color('black')
    t.forward(90)
    t.backward(90)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(90)
    t.backward(90)
    t.left(90)
    t.backward(50)
    t.right(90)
    t.forward(70)
    t.backward(70)
    t.left(90)
    t.backward(50)
    t.right(90)
    t.forward(92)
    t.color('white')
    t.forward(48)

# letra L
def l():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.backward(100)
    t.right(90)
    t.forward(82)
    t.color('white')
    t.forward(58)

# letra F
def f():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(90)
    t.backward(90)
    t.left(90)
    t.backward(50)
    t.right(90)
    t.forward(75)
    t.backward(75)
    t.left(90)
    t.backward(50)
    t.right(90)
    t.forward(3)
    t.color('white')
    t.forward(147)


# letra H
def h():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.backward(50)
    t.right(90)
    t.forward(90)
    t.left(90)
    t.forward(50)
    t.backward(100)
    t.right(90)
    t.forward(3)
    t.color('white')
    t.forward(48)


# letra I
def i():
    t.color('white')
    t.forward(45)
    t.left(90)
    t.color('black')
    t.forward(100)
    t.backward(100)
    t.right(90)
    t.forward(3)
    t.color('white')
    t.forward(142)

# letra T
def T():
    t.color('white')
    t.forward(45)
    t.color('black')
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(45)
    t.backward(90)
    t.forward(45)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(3)
    t.color('white')
    t.forward(142)


# letra D
def d():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(80)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.forward(60)
    t.right(45)
    t.forward(30)
    t.right(45)
    t.forward(80)
    t.backward(83)
    t.color('white')
    t.backward(57)

# letra M(temporaria)
def m():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(70)
    t.backward(70)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.forward(3)
    t.color('white')
    t.forward(48)


# letra N
def n():
    t.color('black')
    t.left(90)
    t.forward(100)
    t.right(145)
    t.forward(120)
    t.left(145)
    t.forward(100)
    t.right(90)
    t.forward(3)
    t.right(90)
    t.color('white')
    t.forward(100)
    t.left(90)
    t.forward(47)


# letra U
def u():
    t.color('white')
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(3)
    t.right(90)
    t.color('black')
    t.forward(80)
    t.left(45)
    t.forward(20)
    t.left(45)
    t.forward(70)
    t.left(45)
    t.forward(20)
    t.left(45)
    t.forward(80)
    t.right(90)
    t.forward(3)
    t.right(90)
    t.color('white')
    t.forward(100)
    t.left(90)
    t.forward(47)

